version: "{build}"

init:
  - git config --global core.autocrlf input

clone_folder: c:\projects\CMakeHelloWorld

shallow_clone: false

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      COMPILER: "Visual Studio 14"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      COMPILER: "Visual Studio 14 Win64"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      COMPILER: "Visual Studio 14"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      COMPILER: "Visual Studio 14 Win64"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      COMPILER: "Visual Studio 15"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      COMPILER: "Visual Studio 15 Win64"

matrix:
  # This is so that if any of the above builds fails, then the whole build fails early.
  fast_finish: true

configuration:
  - Release

platform:
  # Set to 'Any CPU', as it is the COMPILER string listed above that tells
  # cmake to pick a generator for either a 64 or 32 bit build.
  - Any CPU

before_build:
- cmd: |
    echo --------------------------------------------------------------------------------
    echo "COMPILER=%COMPILER%, CONFIGURATION=%CONFIGURATION%"
    cmake -version
    pwd
    git submodule update -q --init --recursive
    echo "PATH=%PATH%"
    echo --------------------------------------------------------------------------------

build_script:
- cmd: |
    echo --------------------------------------------------------------------------------
    mkdir build
    cd build
    cmake -G "%COMPILER%"  -DBUILD_TESTING:BOOL=ON --config %CONFIGURATION% ..
    cmake --build . --config %CONFIGURATION%
    echo --------------------------------------------------------------------------------

test_script:
- cmd: |
    echo --------------------------------------------------------------------------------
    pwd
    ctest -C %CONFIGURATION%
    echo --------------------------------------------------------------------------------
